### PR TITLE
Cleanup and fix for Turkish characters ü,ö,ğ,ș,ı

### PR DESCRIPTION
**Pull request by adamsocrat**
Cleanup and fix for Turkish characters ü,ö,ğ,ș,ı

### CODE REVIEW

**Comment by ojwb** [comment]
Your proposed change causes the tests in snowball to fail, e.g.:

```
$ make check_utf8_turkish
Checking output of turkish stemmer with UTF-8
--- ../snowball-data/turkish/output.txt	2024-01-11 13:56:43.858276033 +1300
+++ tmp.txt	2024-07-16 07:32:01.393728619 +1200
@@ -1,36 +1,3 @@
-a
-a'
-a'
-a'
-a'n
-a'ya
```

and much much more.

Given you appear to have changed 5000+ vocabulary entries that's not really a surprise:

```
$ git show --stat 
commit 1e6e9bab774689134aff79e40accf9901ed96ea6 (HEAD)
Author: Yunus Can Sakallı <43264230+adamsocrat@users.noreply.github.com>
Date:   Mon Jul 15 16:27:50 2024 +0300

    Cleanup and fix for Turkish characters ü,ö,ğ,ș,ı

 turkish/voc.txt | 10764 ++++++++++++++++++++++++++----------------------------
 1 file changed, 5148 insertions(+), 5616 deletions(-)
```

So I just can't merge this as-is.

I think you need to start by explaining the problem you think needs addressing here.

**Comment by ojwb** [comment]
Updating the expected output likely solves the problem of the tests failing.

However this is still a sweeping change to the test data so (as I already asked once) can you please explain the problem you think needs addressing here.

The diff is too huge to easily divine your motivation, and "Cleanup and fix for Turkish characters ü,ö,ğ,ș,ı" hints at **what** but doesn't explain **WHY**.

**Comment by adamsocrat** [comment]
The test data does not accurate and pointed towards to testing ability to stem Turkish words. I wanted to implement Turkish for nltk so had to first fix the test data. It is especially hard to implement it since it is suffix driven language rather than word driven. e.g. The word "doktoruymuşsunuz" means "You had been the doctor of him". 

also

I cannot understand why nltk does not support Turkish [here](https://www.nltk.org/api/nltk.stem.SnowballStemmer.html?highlight=stopwords#nltk.stem.SnowballStemmer), but has a working algorithm [here](https://snowballstem.org/algorithms/turkish/stemmer.html). Is nltk has its own SnowballStemmer instead of using this repo  snowball-stem.

**Comment by ojwb** [comment]
You've now closed this PR - does this mean you don't want me to consider these changes?

> I cannot understand why nltk does not support Turkish [here](https://www.nltk.org/api/nltk.stem.SnowballStemmer.html?highlight=stopwords#nltk.stem.SnowballStemmer), but has a working algorithm [here](https://snowballstem.org/algorithms/turkish/stemmer.html). Is nltk has its own SnowballStemmer instead of using this repo snowball-stem?

You'd really need to ask the nltk developers, but my guess would be that they have an embedded copy Snowball and haven't synced it with a Snowball release for a long time.  The odd thing is your link says they have Arabic but that was added **after** Turkish (also after Tamil) - I guess they have patched in Arabic themselves?

**Comment by adamsocrat** [comment]
> You've now closed this PR - does this mean you don't want me to consider these changes?

Yes, until I figure everthing out.


> > I cannot understand why nltk does not support Turkish [here](https://www.nltk.org/api/nltk.stem.SnowballStemmer.html?highlight=stopwords#nltk.stem.SnowballStemmer), but has a working algorithm [here](https://snowballstem.org/algorithms/turkish/stemmer.html). Is nltk has its own SnowballStemmer instead of using this repo snowball-stem?
> 
> You'd really need to ask the nltk developers, but my guess would be that they have an embedded copy Snowball and haven't synced it with a Snowball release for a long time. The odd thing is your link says they have Arabic but that was added **after** Turkish (also after Tamil) - I guess they have patched in Arabic themselves?

No idea will look into it.

**Pull request closed without merging**
